version: "3.5"
services:
    db:
        image: postgres
        container_name: "${DB_CONTAINER}"
        environment:
            POSTGRES_DB: "${DB_NAME}"
            POSTGRES_USER: "${DB_USER}"
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
        ports:
            - "${DB_PORT}:5432"
